out_dir: results/ogb/ogbg
custom_metrics: ['ogbg_molpcba_average_precision']
metric_best: 'ogbg_molpcba_average_precision'
dataset:
  format: OGB
  name: ogbg-molpcba
  task: graph
  task_type: classification_binary
  node_encoder: true
  node_encoder_name: Atom
  edge_encoder: true
  edge_encoder_name: Bond
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 16
  layer_type: gainconv
  stage_type: stack
  batchnorm: true
  act: prelu
  dropout: 0.0
  agg: add
  normalize_adj: false
  use_edge_attr: true
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 200
